scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgresql-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgresql-exporter:9187']
